name: PlantUML Diagrams

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-diagrams:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install PlantUML
      run: sudo apt-get install plantuml

    - name: Download C4-PlantUML library
      run: |
        mkdir -p plantuml-libs
        wget -O plantuml-libs/C4_Context.puml https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
        wget -O plantuml-libs/C4_Container.puml https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
        wget -O plantuml-libs/C4_Component.puml https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

    - name: Generate Diagrams
      run: |
        cd plantuml-libs && plantuml ../diagrams/context/*.puml || true
        cd plantuml-libs && plantuml ../diagrams/container/*.puml || true
        cd plantuml-libs && plantuml ../diagrams/component/*.puml || true
        cd plantuml-libs && plantuml ../diagrams/code/*.puml || true

    - name: Commit Diagrams
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add diagrams/**/*.png
        git commit -m "Automated diagram generation"
        git push
      if: success()
